package com.zen.alchan.helper.enums

import android.graphics.Color
import androidx.annotation.ColorInt
import androidx.annotation.DrawableRes
import com.zen.alchan.R
import com.zen.alchan.helper.extensions.convertFromSnakeCase

/**
 * key, hexColor, icon no longer used
 */

enum class OtherLink(val id: Int, val siteName: String, val mediaType: MediaType) {
    // English
    CRUNCHYROLL(5, "Crunchyroll", MediaType.ANIME),
    CRUNCHYROLL_MANGA(6, "Crunchyroll", MediaType.MANGA),
    HULU(7, "Hulu", MediaType.ANIME),
    FUNIMATION(8, "Funimation", MediaType.ANIME),
    NETFLIX(10, "Netflix", MediaType.ANIME),
    YOUTUBE(13, "Youtube", MediaType.ANIME),
    HIDIVE(20, "HIDIVE", MediaType.ANIME),
    AMAZON(12, "Amazon", MediaType.ANIME),
    VIMEO(22, "Vimeo", MediaType.ANIME),
    VRV(24, "VRV", MediaType.ANIME),
    HBO_MAX(25, "HBO Max", MediaType.ANIME),
    WAKANIM(26, "Wakanim", MediaType.ANIME),
    RETRO_CRUSH(27, "RetroCrush", MediaType.ANIME),
    ADULT_SWIM(28, "Adult Swim", MediaType.ANIME),
    JAPANESE_FILM_ARCHIVES(29, "Japanese Film Archives", MediaType.ANIME),
    TUBI_TV(30, "Tubi TV", MediaType.ANIME),
    CRACKLE(31, "Crackle", MediaType.ANIME),
    ASIAN_CRUSH(32, "AsianCrush", MediaType.ANIME),
    MIDNIGHT_PULP(33, "Midnight Pulp", MediaType.ANIME),
    CONTV(34, "CONtv", MediaType.ANIME),
    MANGA_CLUB(35, "Manga.Club", MediaType.MANGA),
    FAKKU(36, "Fakku", MediaType.ANIME),
    FAKKU_MANGA(37, "Fakku", MediaType.MANGA),
    WEB_COMICS(41, "Web Comics", MediaType.MANGA),
    MANGA_PLUS(42, "Manga Plus", MediaType.MANGA),
    WEBTOONS(43, "Webtoons", MediaType.MANGA),
    TOOMICS(44, "Toomics", MediaType.MANGA),
    BILIBILI(45, "Bilibili", MediaType.ANIME),
    LEZHIN(46, "Lezhin", MediaType.MANGA),
    FUTEKIYA(73, "Futekiya", MediaType.MANGA),
    MANGA_PLANET(74, "Manga Planet", MediaType.MANGA),
    TAPAS(75, "Tapas", MediaType.MANGA),
    TAPPYTOON(77, "Tappytoon", MediaType.MANGA),
    MANTA(80, "Manta", MediaType.MANGA),
    WECOMICS(82, "WeComics", MediaType.MANGA),
    WEBNOVEL(86, "Webnovel", MediaType.MANGA),
    COPIN_COMICS(101, "Copin Comics", MediaType.MANGA),
    MANGATOON(103, "MangaToon", MediaType.MANGA),
    JNOVEL_CLUB(105, "J-Novel Club", MediaType.MANGA),
    BILIBILI_COMICS(107, "Bilibili Comics", MediaType.MANGA),
    LALATOON(113, "Lalatoon", MediaType.MANGA),
    TOPTOON(116, "TOPTOON+", MediaType.MANGA),
    DISNEY_PLUS(118, "Disney Plus", MediaType.ANIME),
    BILIBILI_TV(119, "Bilibili TV", MediaType.ANIME),
    TENCENT_VIDEO(121, "Tencent Video", MediaType.ANIME),
    IQ(122, "iQ", MediaType.ANIME),
    YOUKU(126, "Youku", MediaType.ANIME),
    MANGAPLAZA(128, "MangaPlaza", MediaType.MANGA),
    WETV(131, "WeTV", MediaType.ANIME),
    SHONEN_JUMP(132, "Shonen Jump", MediaType.MANGA),
    AZUKI(153, "Azuki", MediaType.MANGA),
    POCKET_COMICS(154, "Pocket Comics", MediaType.MANGA),
    COMIKEY(157, "Comikey", MediaType.MANGA),
    INKR(159, "INKR", MediaType.MANGA),
    ALPHA_MANGA(163, "Alpha Manga", MediaType.MANGA),
    COOLMIC(169, "Coolmic", MediaType.MANGA),
    NICONICO_VIDEO(180, "Niconico Video", MediaType.ANIME),
    LEZHIN_X(181, "Lezhin X", MediaType.MANGA),
//    TOOMICS(185, "Toomics", MediaType.MANGA), Duplicate in AniList
    ROOSTER_TEETH(195, "Rooster Teeth", MediaType.ANIME),
    MANGA_UP(199, "MANGA UP!", MediaType.MANGA),
    NETCOMICS(201, "Netcomics", MediaType.MANGA),
    IQIYI(204, "iQIYI", MediaType.ANIME),

    // Japanese
    MANGABOX(57, "Mangabox (JP)", MediaType.MANGA),
    COMICWALKER(58, "ComicWalker (JP)", MediaType.MANGA),
    NICO_NICO_SEIGA(59, "Nico Nico Seiga (JP)", MediaType.MANGA),
    PIXIV_COMIC(60, "Pixiv Comic (JP)", MediaType.MANGA),
    PIXIV_NOVEL(61, "Pixiv Novel (JP)", MediaType.MANGA),
    COMICO(62, "Comico (JP)", MediaType.MANGA),
    PICCOMA(63, "Piccoma (JP)", MediaType.MANGA),
    WEBTOONS_JP(64, "Webtoons (JP)", MediaType.MANGA),
    SHONEN_JUMP_PLUS(71, "Shonen Jump Plus (JP)", MediaType.MANGA),
    POCKET_MAGAZINE(72, "Pocket Magazine (JP)", MediaType.MANGA),
    SUNDAY_WEBRY(83, "Sunday Webry (JP)", MediaType.MANGA),
    GANMA(84, "Ganma! (JP)", MediaType.MANGA),
    CYNOMICS(85, "Cycomics (JP)", MediaType.MANGA),
    TONARI_NO_YOUNG_JUMP(87, "Tonari no Young Jump (JP)", MediaType.MANGA),
    MANGA_PARK(88, "Manga Park (JP)", MediaType.MANGA),
    COMIC_DAYS(89, "Comic Days (JP)", MediaType.MANGA),
    COMIC_ZENON(90, "Comic Zenon (JP)", MediaType.MANGA),
    MANGA_LIBRARY_Z(93, "Mnaga Library Z (JP)", MediaType.MANGA),
    MANGA_LOVE(95, "Manga Love (JP)", MediaType.MANGA),
    SUKIMA(96, "Sukima (JP)", MediaType.MANGA),
    COMICESS(97, "Comicess (JP)", MediaType.MANGA),
    MANGA_DOKUHA(98, "Manga Dokuha (JP)", MediaType.MANGA),
    ALPHAPOLIS(99, "Alphapolis (JP)", MediaType.MANGA),
    URA_SUNDAY(100, "Ura SUnday (JP)", MediaType.MANGA),
    COMIC_ESSAY(102, "Comic Essay (JP)", MediaType.MANGA),
    LEZHIN_JP(108, "Lezhin (JP)", MediaType.MANGA),
    KURAGE_BUNCH(110, "Kurage Bunch (JP)", MediaType.MANGA),
    COMIC_ACTION(111, "Comic Action (JP)", MediaType.MANGA),
    LALATOON_JP(114, "Lalatoon (JP)", MediaType.MANGA),
    NEWTYPE_WEB(115, "Newtype Web (JP)", MediaType.MANGA),
    COMIC_FUZ(138, "Comic Fuz (JP)", MediaType.MANGA),
    MANGATOON_JP(139, "MangaToon (JP)", MediaType.MANGA),
    MANGA_CROSS(155, "Manga Cross (JP)", MediaType.MANGA),
    COMIPLEX(156, "Comiplex (JP)", MediaType.MANGA),
    COMIC_METEOR(158, "Comic Meteor (JP)", MediaType.MANGA),
    COMIC_RIDE(160, "Comic Ride (JP)", MediaType.MANGA),
    MAGCOMI(161, "Magcomi (JP)", MediaType.MANGA),
    WEB_ACE(165, "Web Ace (JP)", MediaType.MANGA),
    GANGAN_ONLINE(171, "Gangan Online (JP)", MediaType.MANGA),
    COMIC_TRAIL(172, "Comic Trail (JP)", MediaType.MANGA),
    CIAO_COMICS(179, "Ciao Comics (JP)", MediaType.MANGA),
    TOOMICS_JP(186, "Toomics (JP)", MediaType.MANGA),
    BELTOON(207, "BeLTOON (JP)", MediaType.MANGA),

    // Korean
    LEZHIN_KR(51, "Lezhin (KR)", MediaType.MANGA),
    TOOMICS_KR(52, "Toomics (KR)", MediaType.MANGA),
    JUSTOON(53, "Justoon (KR)", MediaType.MANGA),
    NAVER_WEBTOON(54, "Naver Webtoon (KR)", MediaType.MANGA),
    KAKAOPAGE(55, "KakaoPage (KR)", MediaType.MANGA),
    BOMTOON(56, "Bomtoon (KR)", MediaType.MANGA),
    PEANUTOON(76, "Peanutoon (KR)", MediaType.MANGA),
    COMICO_KR(79, "Comico (KR)", MediaType.MANGA),
    COMICA(81, "Comica (KR)", MediaType.MANGA),
    BUFFTOON(117, "Bufftoon (KR)", MediaType.MANGA),
    NAVER_SERIES(134, "Naver Series (KR)", MediaType.MANGA),
    TOPTOON_KR(136, "TOPTOON (KR)", MediaType.MANGA),
    KAKAO_WEBTOON(137, "Kakao Webtoon (KR)", MediaType.MANGA),
    MANYEO_COMICS(170, "Manyeo Comics (KR)", MediaType.MANGA),
    ANYTOON(173, "Anytoon (KR)", MediaType.MANGA),
    MOOTOON(174, "Mootoon (KR)", MediaType.MANGA),
    KTOON(175, "Ktoon (KR)", MediaType.MANGA),
//    BUFFTOON(176, "Bufftoon (KR)", MediaType.MANGA), Duplicate in AniList
    ONESTORY(177, "Onestory (KR)", MediaType.MANGA),
    BATTLE_COMICS(178, "Battle Comics (KR)", MediaType.MANGA),
    SPOONCOMICS(192, "Spooncomics (KR)", MediaType.MANGA),
    QTOON(203, "QToon (KR)", MediaType.MANGA),
    MANHYAKYUNG(205, "Manhwakyung (KR)", MediaType.MANGA),

    // Chinese
    TENCENT_COMICS(65, "Tencent Comics (CN)", MediaType.MANGA),
    KUAIKAN_MANHUA(66, "KuaiKan Manhua (CN)", MediaType.MANGA),
    WEIBO_MANHUA(68, "Weibo Manhua (CN)", MediaType.MANGA),
    DAJIAOCHONG_MANHUA(69, "Dajiaochong Manhua (CN)", MediaType.MANGA),
    MANMAN_MANHUA(70, "Manman Manhua (CN)", MediaType.MANGA),
    DONGMAN_MANHUA(91, "Dongman Manhua (CN)", MediaType.MANGA),
    MANHUATAI(92, "Manhuatai (CN)", MediaType.MANGA),
    KAI_MANHUA(94, "Kai Manhua (CN)", MediaType.MANGA),
    MANGATOON_CN(104, "MangaToon (CN)", MediaType.MANGA),
    CREATIVE_COMIC_COLLECTION(106, "Creative Comic Collection (CN)", MediaType.MANGA),
    LALATOON_CN(112, "Lalatoon (CN)", MediaType.MANGA),
    MKZHAN(123, "MKZhan (CN)", MediaType.MANGA),
    BILIBILI_CN(124, "Bilibili (CN)", MediaType.MANGA),
    iQIYI_CN(130, "iQIYI (CN)", MediaType.MANGA),
    WEBTOONS_CN(143, "Webtoons (CN)", MediaType.MANGA),
    ZHIYIN_MANKE(150, "Zhiyin Manke (CN)", MediaType.MANGA),
    KANMANHUA(162, "Kanmanhua (CN)", MediaType.MANGA),
    TOPTOON_CN(164, "TOPTOON (CN)", MediaType.MANGA),
    TOOMICS_CN(190, "Toomics (CN)", MediaType.MANGA),
//    TOOMICS_CN(191, "Toomics (CN)", MediaType.MANGA), Duplicate in AniList
    KAKAO_WEBTOON_CN(193, "Kakao Webtoon (CN)", MediaType.MANGA),
    BOMTOON_CN(202, "Bomtoon (CN)", MediaType.MANGA),
    MANHUADAO(206, "Manhuadao (CN)", MediaType.MANGA),

    // Spanish
    LEZHIN_ES(109, "Lezhin (ES)", MediaType.MANGA),
    WEBTOONS_ES(133, "Webtoons (ES)", MediaType.MANGA),
    MANGATOON_ES(140, "MangaToon (ES)", MediaType.MANGA),
    TOOMICS_ES(187, "Toomics (ES)", MediaType.MANGA),

    // Thai
    MANGATOON_TH(141, "MangaToon (TH)", MediaType.MANGA),
    WEBTOONS_TH(144, "Webtoons (TH)", MediaType.MANGA),
    COMICO_TH(149, "Comico (TH)", MediaType.MANGA),
    KAKAO_WEBTOON_TH(152, "Kakao Webtoon (TH)", MediaType.MANGA),
    BOOMTOON_TH(194, "Boomtoon (TH)", MediaType.MANGA),
    WECOMICS_TH(208, "WeComics (TH)", MediaType.MANGA),

    // French
    MANGATOON_FR(142, "MangaToon (FR)", MediaType.MANGA),
    WEBTOONS_FR(145, "Webtoons (FR)", MediaType.MANGA),
    TAPPYTOON_FR(147, "Tappytoon (FR)", MediaType.MANGA),
    DELITOON(151, "Delitoon (FR)", MediaType.MANGA),
    VERYTOON(167, "Verytoon (FR)", MediaType.MANGA),
    TOOMICS_FR(189, "Toomics (FR)", MediaType.MANGA),
    MANGASIO(198, "Mangas.io (FR)", MediaType.MANGA),
    LE_BONTOON(200, "Le Bontoon (FR)", MediaType.MANGA),

    // German
    WEBTOONS_DE(146, "Webtoons (DE)", MediaType.MANGA),
    TAPPYTOON_DE(148, "Tappytoon (DE)", MediaType.MANGA),
    TOOMICS_DE(188, "Toomics (DE)", MediaType.MANGA),
    DELITOON_B(209, "Delitoon B (DE)", MediaType.MANGA)
}

fun OtherLink.getString(): String {
    return siteName
}